idf_component_register(
    SRCS
        "app.c"
        "ui/splash.c"
        "ui/logo_chintamani.c"
        "ui/vent_img.c"
        "ui/car_hero_img.c"
        "ui/van_hero_img.c"
        "ui/ac_state.c"
        "ui/ctrl_state.c"
        "ui/owner_name.c"
        "ui/tile_names.c"
        "ui/display_brightness.c"
        "ui/img_nikola_logo.c"
        "ui/font_cursive_56.c"
        "ui/font_cursive_40.c"
        "ui/ui_theme.c"
        "ui/ui_shell.c"
        "ui/ui_tab_climate.c"
        "ui/ui_tab_control.c"
        "ui/ui_tab_overview.c"
        "ui/ui_tab_maintenance.c"
        "ui/ui_tab_entertainment.c"
        "modbus/modbus_client.c"
        "modbus/modbus_task.c"
        "modbus/modbus_server.c"
        "hvac/hvac_controller.c"
        "sensor/bmp280.c"
        "hmi_role/hmi_role.c"
        "hmi_sync/hmi_sync.c"
        "bus_config/bus_config.c"
        "cloud/hyperwisor_app.c"
    INCLUDE_DIRS
        "include"
        "ui"
        "modbus"
        "hvac"
        "sensor"
        "hmi_role"
        "hmi_sync"
        "bus_config"
        "cloud"
    REQUIRES
        bsp_s3_rgb
        lvgl
        nvs_flash
        esp_timer
        hyperwisor
    PRIV_REQUIRES
        esp_driver_uart
        esp_driver_i2c
)
