"""Convert NikolaIndustry logo PNG into an LVGL ALPHA_8BIT C image.

Monochrome logo (white on transparent) is stored as 1 byte per pixel
(alpha only). LVGL recolors it at draw time using the widget's
img_recolor/img_recolor_opa style, so the logo adopts any tint the
UI wants.

Output: components/app/ui/img_nikola_logo.c (alongside .h declaration)
"""
from PIL import Image
import os, sys

SRC = r"C:\Users\user\AppData\Roaming\Qoder\SharedClientCache\cache\images\2c2ec006\white1-dc078022.png"
OUT_DIR = r"c:\Users\user\Downloads\esp32_p4_deom\hyperwisor_s3\components\app\ui"
W, H = 220, 52

im = Image.open(SRC).convert("LA")
im = im.resize((W, H), Image.LANCZOS)

# For a white-on-transparent logo, the alpha channel IS the mask.
# Multiply alpha by luminance/255 so faint grey pixels don't appear
# fully opaque; keeps the anti-aliased edges clean.
pixels = []
for y in range(H):
    for x in range(W):
        lum, alpha = im.getpixel((x, y))
        # Final opacity = alpha weighted by luminance (0..255)
        a = int(alpha * (lum / 255.0))
        if a > 255: a = 255
        pixels.append(a)

c_path = os.path.join(OUT_DIR, "img_nikola_logo.c")
h_path = os.path.join(OUT_DIR, "img_nikola_logo.h")

with open(h_path, "w") as f:
    f.write("#pragma once\n")
    f.write("#include \"lvgl.h\"\n\n")
    f.write("extern const lv_img_dsc_t img_nikola_logo;\n")

with open(c_path, "w") as f:
    f.write("/* Auto-generated by scripts/gen_nikola_logo.py. Do not edit. */\n")
    f.write("#include \"lvgl.h\"\n\n")
    f.write("static const uint8_t nikola_logo_map[] = {\n")
    for i in range(0, len(pixels), 16):
        row = ", ".join("0x%02x" % p for p in pixels[i:i+16])
        f.write("    " + row + ",\n")
    f.write("};\n\n")
    f.write("const lv_img_dsc_t img_nikola_logo = {\n")
    f.write("    .header.cf = LV_IMG_CF_ALPHA_8BIT,\n")
    f.write("    .header.always_zero = 0,\n")
    f.write("    .header.reserved = 0,\n")
    f.write("    .header.w = %d,\n" % W)
    f.write("    .header.h = %d,\n" % H)
    f.write("    .data_size = %d,\n" % len(pixels))
    f.write("    .data = nikola_logo_map,\n")
    f.write("};\n")

print(f"wrote {c_path} ({len(pixels)} bytes)")
print(f"wrote {h_path}")
